title: Renewal SA WordPress Template
description: A starter template for Renewal SA WordPress Sites
theme: just-the-docs

url: https://renewalsa-websites.github.io/wordpress-template/

logo: "/assets/renewalsa-logo.png"

aux_links:
  Template Repository: https://github.com/renewalsa-websites/wordpress-template
